name: Deploy to vercel on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nexterias/actions-vercel@v2.0.0
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          production: true
          org-id: ${{ secrets.ORG_ID}}
          project-id: ${{ secrets.PROJECT_ID}}
      - name: Purge Cloudflare cache
        run: |
          curl https://api.cloudflare.com/client/v4/zones/${{secrets.CLOUDFLARE_ZONE_ID}}/purge_cache \
          -H 'Content-Type: application/json' \
          -H "Authorization: Bearer ${{secrets.CLOUDFLARE_API_TOKEN}}" \
          -d '{"purge_everything":true}'
